version: 2

lint-debounce: 1s

tools: 

  prettier_d: &prettier_d
    format-command: 'prettierd ${INPUT}'
    format-stdin: true    
  
  eslint_d: &eslint_d 
    format-command: 'eslint_d --no-color --format visualstudio --stdin --fix-to-stdout --stdin-filename ${INPUT}'
    lint-command: 'eslint_d --no-color --format visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    format-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"
    root-markers:
      - ".eslintrc"
      - ".eslintrc.js"
      - ".eslintrc.cjs"
      - ".eslintrc.json"
      - ".eslintrc.yml"
      - ".eslintrc.yaml"
      - "package.json"

languages:

  javascript:
    - <<: *eslint_d
    - <<: *prettier_d

  typescript:
    - <<: *eslint_d
    - <<: *prettier_d
 
  javascriptreact:
    - <<: *eslint_d
    - <<: *prettier_d

  typescriptreact:
    - <<: *eslint_d
    - <<: *prettier_d
    
  javascript.tsx:
    - <<: *eslint_d
    - <<: *prettier_d

  typescript.tsx:
    - <<: *eslint_d
    - <<: *prettier_d

  svelte:
    - <<: *eslint_d
    - <<: *prettier_d