[[language]]
name = "html"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout", "--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout", "--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout", "--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout"] }
language-server = { command = "vscode-eslint-language-server", args = ["--stdio"], language-id = "typescriptreact" }
auto-format = true
config = { "workingDirectory" = "./" }

[[language]]
name = "jsx"
formatter = { command = 'eslint_d', args = ["--stdin", "--fix-to-stdout"] }
auto-format = true


