use-grammars = { only = [ "dart", "go", "rust", "javascript", "jsx", "json", "jsonnet", "typescript", "tsx","yaml" ] }


[language-server.efm-lsp-js]
command = "efm-langserver"

[language-server.efm-lsp-js.config]
documentFormatting = true


[[language]]
name = "typescript"
language-servers = [ { name = "efm-lsp-js", only-features = [ "format" ] }, "typescript-language-server" ]

[[language]]
name = "tsx"
language-servers = [ { name = "efm-lsp-js", only-features = [ "format" ] }, "typescript-language-server" ]

[[language]]
name = "javascript"
language-servers = [ { name = "efm-lsp-js", only-features = [ "format" ] }, "typescript-language-server" ]

[[language]]
name = "jsx"
language-servers = [ { name = "efm-lsp-js", only-features = [ "format" ] }, "typescript-language-server" ]

