use-grammars = { only = [ "bash", "dart", "env", "go", "rust", "lua", "javascript", "jsx", "json", "jsonnet", "typescript", "tsx","yaml" ] }


[language-server.efm-lsp-js]
command = "efm-langserver"

[language-server.efm-lsp-js.config]
documentFormatting = true


[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "    " }
language-servers = ["efm-lsp-js", "typescript-language-server"]
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 4, unit = "    " }
language-servers = ["efm-lsp-js", "typescript-language-server"]
auto-format = true

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "    " }
language-servers = ["efm-lsp-js", "typescript-language-server"]
auto-format = true

[[language]]
name = "jsx"
indent = { tab-width = 4, unit = "    " }
language-servers = ["efm-lsp-js", "typescript-language-server"]
auto-format = true

