"$schema" = 'https://starship.rs/config-schema.json'


# Which is equivalent to
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$sudo\
$character"""

[git_branch]
format = '[$branch]($style) '
style = "bright-black"
symbol = ""

[character]
success_symbol = '[⩔](bold green)'
error_symbol = '[⩔](bold red)'

[hostname]
ssh_only = true
ssh_symbol = ''

[package]
disabled = true
